### ISSUE TITLE
Captcha installation

### ISSUE THREAD

**Issue by waywho** [LensShift/lenshift-v2#10]
We want to install captcha at the sign in and sign up page process to avoid bots trying to sign up or avoid fake sign up accounts.

- [x] Install https://github.com/markets/invisible_captcha

- [x] Integrate captcha with devise gem

- [x] Integrate in the devise controller
- [x] Put captcha on the sign in page

**Comment by RMonteR** [comment]
#https://github.com/LensShift/lenshift-v2/commit/9f378b1b5850427dcaf1ca049a30f2a879454592
From routes.rb:
`  devise_for :lens_shifters, controllers: {
    registrations: "lens_shifters/registrations"
  }`

I would guess the controller related to **/lens_shifters/sign_in** is **lens_shifters/registrations_controller.rb**. But when I look at the code it is not clear to me how.  

I was also looking at **controllers/fellow/lens_shifter_controller.rb** and **app/controllers/profiles_controller.rb. Lens_shifters are normal users, right?

Thank you for any hint!

**Comment by waywho** [comment]
Yes, you are correct. the lens_shifters/registrations_controller.rb is the first controller that we should install captcha. You should look at the [devise gem](https://github.com/plataformatec/devise) for a bit more insight as to how it works.

Lens_shifters are normal users, that is correct. but the **controllers/fellow/lens_shifter_controller.rb** is only accessible for those who are admin/fellows. So we don't need to worry about that one. 

We also should try implement captcha on **app/controllers/profiles_controller.rb** but that would be secondary.
